### ISSUE TITLE
Support markdown and/or HTML in dashboard descriptions

### ISSUE THREAD

**Issue by toolness** [simonw/django-sql-dashboard#115]
In particular, I'm linking out to external sites in my dashboard descriptions, so it would be great to have those hyperlinked (currently the viewer has to manually copy/paste the URL, which is shown as plain text).  Since the package already has both `markdown` and `bleach` as dependencies, it doesn't seem like this should be technically complex, although perhaps making it backwards-compatible might be non-trivial...

Anyways, happy to discuss this further and start a PR if it's deemed a good idea.

**Comment by simonw** [comment]
This is a great idea - especially since we already bundle the Markdown library for other purposes.

I think the simplest solution here would be to say that the dashboard description field supports markdown - I don't expect there to be wide enough deployments of the tool that treating existing descriptions as markdown is likely to break anything significant, though we'll still call it out in the release notes.

**Comment by toolness** [comment]
Nice!  Would you like me to start a PR for this or any of the other issues?  I'm interested in giving back to this codebase but I also understand if you'd rather do things yourself.

**Comment by simonw** [comment]
Would welcome a PR for this!

**Comment by simonw** [comment]
This is now released as version 0.16. https://github.com/simonw/django-sql-dashboard/releases/tag/0.16

**Comment by simonw** [comment]
Demo: https://simonwillison.net/dashboard/example-dashboard/
